### ISSUE TITLE
MoveFromTo's output values are identical

### ISSUE THREAD

**Issue by bstro** [jvoigtlaender/elm-drag-and-drop#1]
Hi! I'm playing around with elm-drag's low level interface and, perhaps I'm misunderstanding something about its use, but upon inspecting the output of the `mouseEvents` signal with a simple  `main = Signal.map show mouseEvents`, the two tuples from `MoveFromTo` are nearly identical no matter where I drag from/to. Is that by design?

![movefromto](https://cloud.githubusercontent.com/assets/627290/15099559/3e650958-150d-11e6-9a3f-e125d6610a08.png)

**Comment by jvoigtlaender** [comment]
Yes, that's as intended. A typical sequence of events on the `mouseEvents` signal would be:
- `StartAt (10,10)`
- `MoveFromTo (10,10) (12,10)`
- `MoveFromTo (12,10) (13,8)`
- `MoveFromTo (13,8) (15,9)`
- `MoveFromTo (15,9) (17,8)`
- `MoveFromTo (17,8) (18,10)`
- `MoveFromTo (18,10) (19,12)`
- `MoveFromTo (19,12) (20,13)`
- `MoveFromTo (20,13) (20,15)`
- `MoveFromTo (20,15) (22,18)`
- `EndAt (22,18)`

if the mouse button was clicked down at position `(10,10)` and then, while the mouse button was still down, the mouse was moved around a bit, and finally the mouse button was released at position `(22,18)`.

**Comment by bstro** [comment]
Oh, I understand completely now. That makes sense. Thanks a lot!
